<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mr.&nbsp;Abraham">

<title>Confidence Intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="confindence_intervals_files/libs/clipboard/clipboard.min.js"></script>
<script src="confindence_intervals_files/libs/quarto-html/quarto.js"></script>
<script src="confindence_intervals_files/libs/quarto-html/popper.min.js"></script>
<script src="confindence_intervals_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="confindence_intervals_files/libs/quarto-html/anchor.min.js"></script>
<link href="confindence_intervals_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="confindence_intervals_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="confindence_intervals_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="confindence_intervals_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="confindence_intervals_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Confidence Intervals</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mr.&nbsp;Abraham </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="confidence-intervals" class="level1">
<h1>5. Confidence Intervals</h1>
<section id="confidence-intervals-1" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-1">5.1 Confidence intervals</h2>
<ul>
<li>Define and compare point estimates and interval estimates.</li>
<li>Define accuracy and precision.</li>
<li>Define confidence intervals, confidence level, and margin of error.</li>
<li>Given margin of error, calculate and interpret a confidence interval.</li>
</ul>
<section id="point-and-interval-estimates" class="level3">
<h3 class="anchored" data-anchor-id="point-and-interval-estimates">Point and interval estimates</h3>
<p>Statistical estimation methods provide estimates for the value of unknown population parameters based on a sample of data. The two statistical estimation methods are point estimates and interval estimates. A <strong><em>point estimate</em></strong> is a single value estimate for an unknown parameter. Ex: A sample of <span class="math inline">\(15\)</span> employees have a mean of <span class="math inline">\(38.4\)</span> hours worked weekly which is a point estimate for the population mean hours worked weekly for all employees at the company. An <strong><em>interval estimate</em></strong> is a range of possible values for the parameter being estimated. Ex: Based on the sample of <span class="math inline">\(15\)</span> employees, a <span class="math inline">\(95\%\)</span> confidence interval for the population mean hours worked weekly is <span class="math inline">\((35.2,41.6)\)</span> .</p>
<p><em>Example 5.1.1: How millennials acquire news.</em></p>
<p>A survey by the Media Insight Project asked a random sample of <span class="math inline">\(1,045\)</span> American adults between the ages of <span class="math inline">\(18\)</span> and <span class="math inline">\(34\)</span> questions about technology used when acquiring news and frequency. The results for a few of the survey questions are given in the table below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Percentage of millennials who:</th>
<th><span class="math inline">\(\%\)</span></th>
<th><span class="math inline">\(95\%\)</span>Confidence interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Say keeping up with the news is at least somewhat important</td>
<td><span class="math inline">\(85\%\)</span></td>
<td><span class="math inline">\((81.2,88.8)\)</span></td>
</tr>
<tr class="even">
<td>Get news daily</td>
<td><span class="math inline">\(69\%\)</span></td>
<td><span class="math inline">\((65.2,72.8)\)</span></td>
</tr>
<tr class="odd">
<td>Regularly follow five or more “hard” news topics</td>
<td><span class="math inline">\(45\%\)</span></td>
<td><span class="math inline">\((41.2,48.8)\)</span></td>
</tr>
<tr class="even">
<td>Usually see diverse opinions through social media</td>
<td><span class="math inline">\(86\%\)</span></td>
<td><span class="math inline">\((82.2,89.8)\)</span></td>
</tr>
<tr class="odd">
<td>Pay for at least one news-specific service, app, or digital subscription</td>
<td><span class="math inline">\(40\%\)</span></td>
<td><span class="math inline">\((36.2,43.8)\)</span></td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What is the point estimate for the percent of millennials who get their news daily?<br>
</li>
<li>What is the <span class="math inline">\(95\%\)</span> confidence interval for the percent of millennials who get their news daily?<br>
</li>
<li>What is the interpretation of this interval estimate?</li>
</ol>
<p><em>Solution</em></p>
<ol type="a">
<li><span class="math inline">\(69\%\)</span><br>
</li>
<li><span class="math inline">\((65.2,72.8)\)</span><br>
</li>
<li>Based on the sample data collected, the true percentage of all millennials who get news daily is believed to be between <span class="math inline">\(65.2\%\)</span> and <span class="math inline">\(72.8\%\)</span> with <span class="math inline">\(95\%\)</span> confidence.</li>
</ol>
</section>
<section id="accuracy-and-precision" class="level3">
<h3 class="anchored" data-anchor-id="accuracy-and-precision">Accuracy and precision</h3>
<p>A good estimation method gives estimates that are both accurate and precise. <strong><em>Accuracy</em></strong> is measured in terms of bias, or how close on average the estimate is to the population parameter being estimated. Numerically, bias is the distance between the mean of the sampling distribution and the population parameter being estimated. <strong><em>Precision</em></strong> is how variable estimates are to one another if the estimation process is repeated. Precision is measured in terms of the standard error of the sampling distribution.</p>
<p>An interval estimate is considered accurate if the interval contains the true population parameter, and an interval estimate’s precision refers to the width of the interval.</p>
<p><em>5.1.1: Accuracy and precision.</em></p>
<p><img width="600" src="https://ap-statistics.web.app/img/stats/5.1.1.gif" controls=""> </p>
<p>Captions:</p>
<ol type="1">
<li>Accuracy is a measure of closeness to the true value of a parameter. Precision is a measure of closeness to the average value of the estimates.</li>
<li>Estimates that are neither accurate nor precise are neither close to the true value nor tightly clustered.</li>
<li>Estimates that are accurate but not precise are loosely spread out around the true value.</li>
<li>Estimates that are precise but not accurate are tightly clustered around an incorrect value.</li>
<li>Estimates that are both accurate and precise are tightly clustered around the true value.</li>
</ol>
</section>
<section id="confidence-intervals-2" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals-2">Confidence intervals</h3>
<p>A <strong><em>confidence interval</em></strong> is an interval estimate constructed such that the probability the method produces an interval that contains the population parameter is given. The percentage of times the method produces a confidence interval containing the parameter is called the <strong><em>confidence level</em></strong>, which is denoted by <span class="math inline">\(c\)</span> . Common values for <span class="math inline">\(c\)</span> are <span class="math inline">\(90\%\)</span> , <span class="math inline">\(95\%\)</span> , and <span class="math inline">\(98\%\)</span> .</p>
<p>A confidence interval is constructed from the sample statistic and margin of error. The <strong><em>margin of error</em></strong>, denoted by <span class="math inline">\(m\)</span> , is a measure of the estimate’s precision and is constructed from a multiplier and the standard error of the statistic’s sampling distribution. The <strong><em>multiplier</em></strong>, or critical value, for a <span class="math inline">\(c\%\)</span> confidence interval is the number of standard deviations about the mean of the sampling distribution that would capture <span class="math inline">\(c\%\)</span> of the distribution.</p>
<p>Numerically: <span class="math display">\[m = (mulitplier)(standard error)\]</span></p>
<p>Therefore: <span class="math display">\[estimate\pm m = estimate\pm(mulitplier)(standard error)\]</span></p>
<p>Confidence intervals are reported either by giving the estimate and margin or error, <span class="math inline">\(estimate\pm m\)</span> , or by calculating and reporting the lower and upper bounds of the interval, <span class="math inline">\((estimate - m, estimate + m)\)</span> .</p>
<p><em>5.1.2: A <span class="math inline">\(95\%\)</span> confidence interval for a population parameter.</em></p>
<p><img width="600" src="https://ap-statistics.web.app/img/stats/5.1.2.gif" controls=""> </p>
<p>Captions: 1. Suppose the true value of the population parameter is <span class="math inline">\(4\)</span> . 2. A sample is drawn from the population. The sample statistic is <span class="math inline">\(3.5\)</span> , so <span class="math inline">\(3.5\)</span> is a point estimate for the population parameter. 3. The margin of error is <span class="math inline">\(\pm2.5\)</span> at a <span class="math inline">\(95\%\)</span> confidence level. Thus, the constructed <span class="math inline">\(95\%\)</span> confidence interval is <span class="math inline">\((3.5 - 2.5, 3.5 + 2.5) = (1,6)\)</span> . 4. The first sample statistic is one possible outcome. The process of drawing a sample from the population and constructing a <span class="math inline">\(95\%\)</span> confidence interval can be repeated. 5. If samples are drawn repeatedly, the percentage of constructed <span class="math inline">\(95\%\)</span> confidence intervals containing the true parameter is <span class="math inline">\(95\%\)</span> , or <span class="math inline">\(19\)</span> of <span class="math inline">\(20\)</span> intervals are expected to contain the true population parameter.</p>
</section>
</section>
<section id="confidence-intervals-for-population-means" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-for-population-means">5.2 Confidence intervals for population means</h2>
<ul>
<li>Define, calculate, and interpret <span class="math inline">\(z\)</span> confidence intervals for population means.</li>
<li>Determine whether a <span class="math inline">\(z\)</span> or <span class="math inline">\(t\)</span> -distribution is suitable for a confidence interval.</li>
<li>Define, calculate, and interpret <span class="math inline">\(t\)</span> confidence intervals for population means.</li>
<li>Calculate the target sample size for a margin of error.</li>
</ul>
<section id="z-confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="z-confidence-intervals"><span class="math inline">\(z\)</span>-confidence intervals</h3>
<p>Choosing an appropriate estimator for the population mean <span class="math inline">\(\mu\)</span> depends on what is known about the population. Although the population mean is usually unknown, the confidence interval that quantifies the range within which the true population mean lies can be calculated by sampling the population. Ex: A <span class="math inline">\(95\%\)</span> confidence interval means that the interval calculated has a <span class="math inline">\(95\%\)</span> probability of containing the population mean. If such a population is sampled <span class="math inline">\(20\)</span> times, <span class="math inline">\(19\)</span> of the <span class="math inline">\(20\)</span> calculated intervals are expected to contain the population mean.</p>
<p><em>5.2.1: The <span class="math inline">\(z\)</span> -confidence interval.</em></p>
<p><img width="600" src="https://ap-statistics.web.app/img/stats/5.2.1.gif" controls=""> </p>
<p>Captions: 1. A confidence interval for the population mean of a normal distribution is calculated from the sample mean <span class="math inline">\(\bar{x}\)</span> , standard deviation <span class="math inline">\(\sigma\)</span> , and number of samples <span class="math inline">\(n\)</span> . 2. The margin of error <span class="math inline">\(m\)</span> for the population mean is equal to <span class="math inline">\(z^*\frac{\sigma}{\sqrt{n}}\)</span> . 3. The confidence level <span class="math inline">\(c\)</span> is the area under the normal distribution curve in the interval <span class="math inline">\((\bar{x} - m, \bar{x} + m)\)</span> . 4. The significance level <span class="math inline">\(\alpha\)</span> is the area under the curve outside the confidence interval.</p>
<p>The critical values <span class="math inline">\(z^*\)</span> for common confidence levels are shown in the following table.</p>
<p><em>Table 5.2.1: Critical values for common confidence levels.</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Confidence level</th>
<th>Critical value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(c=0.90\)</span></td>
<td><span class="math inline">\(z^*=1.645\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(c=0.95\)</span></td>
<td><span class="math inline">\(z^*=1.960\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(c=0.99\)</span></td>
<td><span class="math inline">\(z^*=2.576\)</span></td>
</tr>
</tbody>
</table>
<p><em>Example 5.2.1: Confidence interval for the mean final grade.</em></p>
<p>Suppose the mean final grade is estimated for all introductory statistics classes taught at a particular college. The population standard deviation is <span class="math inline">\(4\)</span> . The final grades for a randomly selected statistics class with <span class="math inline">\(9\)</span> people are: <span class="math inline">\(76\)</span> , <span class="math inline">\(80\)</span> , <span class="math inline">\(82\)</span> , <span class="math inline">\(83\)</span> , <span class="math inline">\(83\)</span> , <span class="math inline">\(85\)</span> , <span class="math inline">\(85\)</span> , <span class="math inline">\(87\)</span> , and <span class="math inline">\(88\)</span> . Find the <span class="math inline">\(95\%\)</span> confidence interval for the mean final grade.</p>
<p><em>Solution</em></p>
<p>The sample mean is <span class="math display">\[\bar{x} = \frac{76+80+82+83+83+85+85+87+88}{9} = 83.222\]</span> At the <span class="math inline">\(95\%\)</span> confidence level, <span class="math inline">\(z^* = 1.960\)</span> , so the margin of error is <span class="math display">\[m = z^*\frac{\sigma}{\sqrt{n}}\]</span> <span class="math display">\[= 1.960*\frac{4}{\sqrt{9}}\]</span> <span class="math display">\[\approx 2.613\]</span> Thus, the <span class="math inline">\(95\%\)</span> confidence interval is <span class="math inline">\((83.222 - 2.613, 83.222 + 2.613) = (80.609, 85.835)\)</span> .</p>
<p>The population mean final grade is generally unknown. The obtained interval means that a <span class="math inline">\(95\%\)</span> confidence exists that <span class="math inline">\((80.609, 85.835)\)</span> contains the true population mean final grade.</p>
<p><em>TI-84CE</em></p>
<video width="600" height="400" src="https://ap-statistics.web.app/img/stats/5.2.1.mp4" controls="">
</video>
</section>
<section id="margin-of-error-and-sample-size-for-means-when-sigma-is-known" class="level3">
<h3 class="anchored" data-anchor-id="margin-of-error-and-sample-size-for-means-when-sigma-is-known">Margin of error and sample size for means when <span class="math inline">\(\sigma\)</span> is known</h3>
<p>The width of the confidence interval is twice the margin of error. Recall that the margin of error depends on the confidence level and the standard error. Thus, given a confidence level, the width of the confidence interval changes by changing the standard error. Increasing the sample size decreases the standard error. Similarly, decreasing the sample size increases the standard error. The size of the sample needed to guarantee a confidence interval with a specified margin of error is given by the formula <span class="math display">\[n = (\frac{z^*\sigma}{m})^2\]</span> To help guarantee a confidence interval with a margin of error no greater than desired, the result of the above equation is rounded up to the nearest whole number sample size.</p>
<p><em>Example 5.2.2: Microbeads in a water reservoir.</em></p>
<p>Scientists study the amount of microbeads (in <span class="math inline">\(\mu\)</span> g/liter) in a water reservoir. The scientists need to know how many water samples should be taken to be <span class="math inline">\(95\%\)</span> confident that their estimate <span class="math inline">\(\bar{x}\)</span> differs from the actual value <span class="math inline">\(\mu\)</span> by at most <span class="math inline">\(0.8 \mu\)</span> g/liter given a population standard deviation of <span class="math inline">\(\sigma = 2.5 \mu\)</span> g/liter. How many water samples should the scientists take?</p>
<p><em>Solution</em></p>
<p>The margin of error is <span class="math inline">\(m = 0.8\)</span> and the population standard deviation is <span class="math inline">\(\sigma = 2.5\)</span> . Since the confidence level is <span class="math inline">\(95\%\)</span> , the critical value is <span class="math inline">\(z^* = 1.960\)</span> . Using the formula above,</p>
<p><span class="math display">\[n = (\frac{z^*\sigma}{m})^2 = (\frac{1.960 * 2.5}{0.8})^2 \approx 37.516\]</span> Thus, the scientists should take at least <span class="math inline">\(38\)</span> water samples.</p>
<p>The value obtained for <span class="math inline">\(n\)</span> should always be rounded up, instead of simply rounded to the nearest integer. Using <span class="math inline">\(37\)</span> water samples, for example, would not be sufficient to guarantee a confidence interval with a specific width.</p>
</section>
<section id="t-confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="t-confidence-intervals"><span class="math inline">\(t\)</span>-confidence intervals</h3>
<p>The confidence interval for a population mean is defined as</p>
<p><span class="math display">\[(\bar{x} - z^* \frac{\sigma}{\sqrt{n}}, \bar{x} + z^* \frac{\sigma}{\sqrt{n}})\]</span></p>
<p>In practice, however, the population standard deviation is rarely known. Thus, confidence intervals using the <span class="math inline">\(t\)</span> -distribution are more useful because the sample standard deviation can always be computed.</p>
<p>The <span class="math inline">\(t\)</span> -confidence interval is given by</p>
<p><span class="math display">\[(\bar{x} - t^* \frac{s}{\sqrt{n}}, \bar{x} + t^* \frac{s}{\sqrt{n}})\]</span></p>
<p>where <span class="math inline">\(t^*\)</span> is the critical value that depends on the degrees of freedom and significance level. The values for common significance levels given selected degrees of freedom are shown in the table below.</p>
<p><em>Table 5.2.2: Critical values <span class="math inline">\(t^*\)</span> for selected degrees of freedom <span class="math inline">\(df\)</span> and significance level <span class="math inline">\(\alpha\)</span>.</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\alpha=0.1\)</span></th>
<th><span class="math inline">\(\alpha=0.05\)</span></th>
<th><span class="math inline">\(\alpha=0.01\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(df=5\)</span></td>
<td><span class="math inline">\(2.015\)</span></td>
<td><span class="math inline">\(2.571\)</span></td>
<td><span class="math inline">\(4.032\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(df=10\)</span></td>
<td><span class="math inline">\(1.812\)</span></td>
<td><span class="math inline">\(2.228\)</span></td>
<td><span class="math inline">\(3.169\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(df=15\)</span></td>
<td><span class="math inline">\(1.753\)</span></td>
<td><span class="math inline">\(2.131\)</span></td>
<td><span class="math inline">\(2.947\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(df=24\)</span></td>
<td><span class="math inline">\(1.711\)</span></td>
<td><span class="math inline">\(2.064\)</span></td>
<td><span class="math inline">\(2.797\)</span></td>
</tr>
</tbody>
</table>
<p><em>Example 5.2.3: Circumference of basketballs</em></p>
<p>The mean circumference of basketballs produced in a manufacturing facility is supposed to be <span class="math inline">\(29\)</span> inches. A random sample of <span class="math inline">\(25\)</span> basketballs has a mean of <span class="math inline">\(29.1\)</span> inches with a sample standard deviation of <span class="math inline">\(0.217\)</span> inches. Find the confidence interval at the <span class="math inline">\(\alpha = 0.01\)</span> significance level.</p>
<p><em>Solution</em></p>
<p>At a significance level of <span class="math inline">\(\alpha = 0.01\)</span> , the confidence level is <span class="math inline">\(99\%\)</span> . The critical value that corresponds to a <span class="math inline">\(99\%\)</span> confidence level and degrees of freedom <span class="math inline">\(df = 25 - 1 = 24\)</span> is <span class="math inline">\(t^* = 2.797\)</span> from the table above. Thus, the margin of error is</p>
<p><span class="math display">\[m = t^* \frac{s}{\sqrt{n}} = 2.797\frac{0.217}{\sqrt{25}} \approx 0.121\]</span></p>
<p>Thus, the <span class="math inline">\(99\%\)</span> confidence interval is</p>
<p><span class="math display">\[(\bar{x} - m, \bar{x} + m) = (29.1 - 0.121, 1 + 0.121) = (28.979, 29.221)\]</span></p>
<p>The obtained confidence interval suggests that a <span class="math inline">\(99\%\)</span> confidence exists that the true population mean circumference of basketballs produced in the facility is between <span class="math inline">\(28.979\)</span> and <span class="math inline">\(29.221\)</span> inches.</p>
<p><em>TI-84CE</em></p>
<video width="600" height="400" src="https://ap-statistics.web.app/img/stats/5.2.3.mp4" controls="">
</video>
</section>
<section id="margin-of-error-and-sample-size-for-means-when-sigma-is-unknown" class="level3">
<h3 class="anchored" data-anchor-id="margin-of-error-and-sample-size-for-means-when-sigma-is-unknown">Margin of error and sample size for means when <span class="math inline">\(\sigma\)</span> is unknown</h3>
<p>The <span class="math inline">\(z\)</span> -distribution is commonly used to estimate the necessary sample size for a survey. Since the population standard deviation is generally unknown, the <span class="math inline">\(t\)</span> -distribution should be used instead. For a situation with an unknown population standard deviation, the sample standard deviation should be used. Thus, <span class="math display">\[n = (\frac{t^*s}{m})^2\]</span> where <span class="math inline">\(t^*\)</span> is the <span class="math inline">\(t\)</span> critical value at a specified confidence level, <span class="math inline">\(s\)</span> is the sample standard deviation based on a preliminary study, and <span class="math inline">\(m\)</span> is the margin of error.</p>
<p>However, <span class="math inline">\(t^*\)</span> depends on the degrees of freedom <span class="math inline">\(n - 1\)</span> , which is also in terms of <span class="math inline">\(n\)</span> . To find <span class="math inline">\(t^*\)</span> , <span class="math inline">\(z^*\)</span> is used to find a preliminary sample size <span class="math inline">\(n^*\)</span> . That is, <span class="math display">\[n^* = (\frac{z^*s}{m})^2\]</span> Then <span class="math inline">\(n\)</span> can be calculated using <span class="math display">\[n = (\frac{t^*s}{m})^2\]</span> where <span class="math inline">\(t^*\)</span> is found using <span class="math inline">\(df = n^* - 1\)</span> . To help guarantee a confidence interval with a margin of error no greater than desired, the result of the above equation is rounded up to the nearest whole number sample size.</p>
<p><em>Example 5.2.4: Quality control.</em></p>
<p>A quality control department in a company wants to estimate the average length of a part to within a margin of error <span class="math inline">\(\pm0.35\)</span> cm at <span class="math inline">\(95\%\)</span> confidence interval. A preliminary pilot study found that the sample standard deviation of the length of parts is <span class="math inline">\(2.50\)</span> cm. How many parts should the department use?</p>
<p><em>Solution</em></p>
<p>The formula above uses <span class="math inline">\(t^*\)</span> , and thus a preliminary sample size <span class="math inline">\(n^*\)</span> is needed. To find <span class="math inline">\(n^*\)</span> , <span class="math inline">\(z^*\)</span> is used in the formula instead of <span class="math inline">\(t^*\)</span> . Since <span class="math inline">\(z^* = 1.960\)</span> at the <span class="math inline">\(95\%\)</span> confidence level, <span class="math display">\[n^* = (\frac{z^*s}{m})^2 = (\frac{1.960 * 2.50}{0.35})^2 = 196\]</span> The critical <span class="math inline">\(t\)</span> value that corresponds to <span class="math inline">\(df = n^* - 1 = 196 - 1 = 195\)</span> at the <span class="math inline">\(95\%\)</span> confidence level is <span class="math inline">\(t^* = 1.972\)</span> . For a <span class="math inline">\(95\%\)</span> confidence interval, the percentile of the <span class="math inline">\(t\)</span> -distribution to find the critical value is <span class="math inline">\(1 - \frac{1-0.95}{2}=0.975\)</span> . The critical value can be found using <span class="math inline">\(t^* = invT(0.975, 195) = 1.972\)</span> . Thus, <span class="math display">\[n^* = (\frac{t^*s}{m})^2 = (\frac{1.972 * 2.50}{0.35})^2 \approx 198.407\]</span> Rounding this result up to the nearest whole number, the quality control department should use a sample size of <span class="math inline">\(199\)</span> parts.</p>
<p>If the sample size was instead rounded down to 198, then the expected margin of error is <span class="math inline">\(1.972 * \frac{2.50}{\sqrt{198}} \approx 0.3504\)</span> , which is slightly higher than the desired 0.35. Rounding the sample size up to 199 gives an expected margin of error of <span class="math inline">\(1.972 * \frac{2.50}{\sqrt{199}} \approx 0.3495\)</span> .</p>
<p><em>TI-84CE</em></p>
<video width="600" height="400" src="https://ap-statistics.web.app/img/stats/5.2.4.mp4" controls="">
</video>
</section>
</section>
<section id="confidence-intervals-for-population-proportions" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-for-population-proportions">5.3 Confidence intervals for population proportions</h2>
<ul>
<li>Define, calculate, and interpret <span class="math inline">\(z\)</span> confidence intervals for population proportions.</li>
<li>Calculate the target sample size for a margin of error.</li>
</ul>
<section id="confidence-interval-for-population-proportions" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-for-population-proportions">Confidence interval for population proportions</h3>
<p>Constructing a confidence interval for a population proportion is similar to constructing a confidence interval for population means. Suppose the sample proportion <span class="math inline">\(\hat{p}\)</span> and the number of samples <span class="math inline">\(n\)</span> are known from sampling the population. The margin of error <span class="math inline">\(m\)</span> is given by <span class="math inline">\(m = z^*\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span> , where <span class="math inline">\(z^*\)</span> is the critical value corresponding to the desired confidence level <span class="math inline">\(c\)</span> . The confidence interval for the population proportion <span class="math inline">\(p\)</span> is given by <span class="math inline">\((\hat{p} - m, \hat{p} + m)\)</span> .</p>
<p><em>Example 5.3.1: Confidence interval for the proportion.</em></p>
<p>In a survey of <span class="math inline">\(1200\)</span> randomly selected registered voters in a particular city, <span class="math inline">\(348\)</span> people are in favor of banning public smoking. State and interpret the <span class="math inline">\(95\%\)</span> confidence interval for the population proportion of voters in favor of banning public smoking.</p>
<p><em>Solution</em></p>
<p>The sample proportion is <span class="math display">\[\hat{p} = \frac{348}{1200} = 0.29\]</span> At the <span class="math inline">\(95\%\)</span> confidence level, the margin of error is <span class="math display">\[m = z^*\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} = 1.960\sqrt{\frac{0.29(1-0.29)}{1200}} \approx 0.026\]</span> Thus, the <span class="math inline">\(95\%\)</span> confidence interval is <span class="math display">\[(\hat{p} - m, \hat{p} + m) = (0.29 - 0.026, 0.29 + 0.026) = (0.264, 0.316)\]</span> The <span class="math inline">\(95\%\)</span> confidence level suggests that if the same estimator was used to construct the interval, then the true population parameter would be within the interval <span class="math inline">\(95\%\)</span> of the time. The obtained confidence interval suggests a <span class="math inline">\(95\%\)</span> confidence exists that the true proportion of voters who favor banning smoking is between <span class="math inline">\(26.4\%\)</span> and <span class="math inline">\(31.6\%\)</span> .</p>
<p><em>TI-84CE</em></p>
<video width="600" height="400" src="https://ap-statistics.web.app/img/stats/5.3.1.mp4" controls="">
</video>
</section>
<section id="margin-of-error-and-sample-size-for-proportions" class="level3">
<h3 class="anchored" data-anchor-id="margin-of-error-and-sample-size-for-proportions">Margin of error and sample size for proportions</h3>
<p>Finding the necessary sample size given a confidence level and margin of error is similar to finding the sample size for a confidence interval for population means. The size of the sample needed to guarantee a confidence interval with a specified margin of error is given by the formula <span class="math display">\[n = (\frac{z^*}{m})^2p(1-p)\]</span> where <span class="math inline">\(z^*\)</span> is the critical value at a specified confidence level, <span class="math inline">\(p\)</span> is the proportion, and <span class="math inline">\(m\)</span> is the margin of error. To help guarantee a confidence interval with a margin of error no greater than desired, the result of the above equation is rounded up to the nearest whole number sample size.</p>
<p>However, <span class="math inline">\(p\)</span> also depends on <span class="math inline">\(n\)</span> . Two possible options exist:</p>
<ol type="1">
<li>A preliminary value for <span class="math inline">\(p\)</span> can be used based on a previous study.</li>
<li>The worst case scenario with <span class="math inline">\(p = 0.50\)</span> can be used, which provides the largest sample size needed to satisfy the required margin of error at a specified confidence level.</li>
</ol>
<p><em>Example 5.3.2: Six months after Brexit.</em></p>
<p>Brexit is a popular term for the successful referendum on June 2016 for the withdrawal of the United Kingdom from the European Union. Six months later, a poll conducted by CNN and ComRes resulted in <span class="math inline">\(47\%\)</span> of the respondents voting to leave the European Union had the referendum been held that day. If the margin of error is <span class="math inline">\(\pm 2.17\)</span> percentage points, find the sample size needed for a <span class="math inline">\(90\%\)</span> confidence interval if</p>
<ol type="a">
<li><span class="math inline">\(p = 0.47\)</span> is used<br>
</li>
<li>no previous estimate is given</li>
</ol>
<p><em>Solution</em></p>
<ol type="a">
<li><p>The margin of error is <span class="math inline">\(m = 0.0217\)</span> . Since a previous estimate is known, the sample proportion is <span class="math inline">\(p=0.47\)</span> . Since the confidence level is <span class="math inline">\(90\%\)</span> , the critical value is <span class="math inline">\(z^* = 1.645\)</span> . Using the formula above, <span class="math display">\[n = (\frac{z^*}{m})^2p(1-p) = (\frac{1.645}{0.0217})^20.47(1-0.47) \approx 1431.483\]</span> Rounding this result up to the nearest whole number, the pollsters sampled at least <span class="math inline">\(1432\)</span> voting aged adults.</p></li>
<li><p>When no previous estimate is known, <span class="math inline">\(p = 0.5\)</span> is used. Using the same formula gives, <span class="math display">\[n = (\frac{z^*}{m})^2p(1-p) = (\frac{1.645}{0.0217})^20.50(1-0.50) \approx 1436.655\]</span> Thus, the pollsters would have sampled <span class="math inline">\(1437\)</span> voting aged adults if no previous estimate is given in the news story.</p></li>
</ol>
<p><em>5.3.2: Confidence intervals for population proportions (two-tailed).</em></p>
<p>Understanding student demographics is important for a college in deciding what programs will most benefit students. A sample of students is taken to determine what proportion of students identify as Hispanic or Latino. The results of the sample are shown below.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Student sample</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hispanic/Latino (x)</td>
<td>90</td>
</tr>
<tr class="even">
<td>Sample size (n)</td>
<td>450</td>
</tr>
<tr class="odd">
<td>Confidence Level</td>
<td>99%</td>
</tr>
<tr class="even">
<td>Critical Value</td>
<td>2.576</td>
</tr>
<tr class="odd">
<td>Margin of Error</td>
<td>0.049</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What is the population parameter?<br>
</li>
<li>What is the point estimate for the population proportion?<br>
</li>
<li>The data suggests a or Latino is between <span class="math inline">\((\ ,\ )\)</span> .</li>
</ol>
<p><em>Solution</em></p>
<ol type="a">
<li>The proportion of all students at the college that identify as Hispanic or Latino<br>
</li>
<li><span class="math inline">\(0.20\)</span><br>
</li>
<li><span class="math inline">\((0.151,0.249)\)</span></li>
</ol>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>